"""Blueprint entrypoint: picks which agent this process runs.

Two ways in, because the two runtimes disagree on how an agent is selected.
Locally (`uv run . <agent>`, `make <agent>`, `docker run ... <agent>`) it is
argv[1]. On a cluster the Deployment is rendered with no command and no args,
so AGENT_MODE is the only selector available. argv wins when present, so a
local run always overrides a stale env var.

The block between the `bat:agents` markers is generated by `bat add agent`
from blueprint.yaml. Edit the rest of this file freely; that block will be
rewritten. Its imports are static and lazy on purpose: PyInstaller has to see
them to freeze them into the binary, and importing inside the branch keeps one
agent's dependencies off another agent's startup path.
"""

import os
import sys


# bat:agents:begin -- generated by `bat add agent`; do not edit by hand
APPS: set[str] = set()


def _load(app: str):
    raise SystemExit(f"Unknown agent: {app}")


# bat:agents:end


def main() -> None:
    if len(sys.argv) > 1:
        app = sys.argv[1]
        sys.argv = sys.argv[1:]
    else:
        app = os.getenv("AGENT_MODE", "")

    if app not in APPS:
        known = "|".join(sorted(APPS)) or "none yet -- run `bat add agent`"
        print(f"Usage: agent <{known}>")
        print("(or set AGENT_MODE to one of the same values)")
        sys.exit(1)

    _load(app)()


if __name__ == "__main__":
    main()
