"""Blueprint entrypoint: runs the agent named by the first argument.

Every way in passes the agent as argv[1]: `uv run . <agent>` and
`make <agent>` locally, the service's `command` in docker-compose.yaml, and
the deployment mode's `args` on a cluster. The rest of argv is handed on to
the agent.

The block between the `bat:agents` markers is generated by `bat add agent`
from the agent directories on disk. Edit the rest of this file freely; that
block will be rewritten. Its imports are static and lazy on purpose:
PyInstaller has to see them to freeze them into the binary, and importing
inside the branch keeps one agent's dependencies off another agent's startup
path.
"""

import sys


# bat:agents:begin -- generated by `bat add agent`; do not edit by hand
APPS: set[str] = set()


def _load(app: str):
    raise SystemExit(f"Unknown agent: {app}")


# bat:agents:end


def main() -> None:
    app = sys.argv[1] if len(sys.argv) > 1 else ""
    if app not in APPS:
        known = "|".join(sorted(APPS)) or "none yet -- run `bat add agent`"
        print(f"Usage: __BLUEPRINT_NAME__ <{known}>")
        sys.exit(1)
    sys.argv = sys.argv[1:]

    _load(app)()


if __name__ == "__main__":
    main()
