"""Scaffold a standalone agent: one uv project, one agent."""

import re
from pathlib import Path

from project import PRIVACY_LEVELS

from .rendering import ensure_empty_dir, render, template_files, write_files

# Naming a pre-release lets the resolver pick one at all (PEP 440).
# Keep in sync with the bat-adk floor in cli/pyproject.toml.
BAT_ADK_VERSION = "2026.10.9a0"

TEMPLATES_DIR = Path(__file__).resolve().parent / "templates" / "agent"
_CLIENT_TEMPLATE = TEMPLATES_DIR / "llm_client.py.template"

# The env var each provider's SDK reads its API key from.
PROVIDER_API_KEY_VAR = {
    "openai": "OPENAI_API_KEY",
    "anthropic": "ANTHROPIC_API_KEY",
    "deepseek": "DEEPSEEK_API_KEY",
    "nvidia": "API_KEY",
}

_CLIENTS_INIT_HEADER = (
    "# Auto-generated by bat-cli (init agent / add client); re-exports every\n"
    "# LLM client in this package. Edits may be overwritten on the next run.\n"
)
_CLASS = re.compile(r"^class\s+(\w+)\s*\(", re.MULTILINE)


def _words(raw: str) -> list[str]:
    """``raw`` split at case changes and non-alphanumerics: RNGClient ->
    RNG, Client."""
    spaced = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1 \2", raw)
    spaced = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", spaced)
    return re.findall(r"[A-Za-z0-9]+", spaced)


def _pascal(raw: str) -> str:
    """``raw`` in PascalCase, without a trailing "agent"."""
    words = _words(raw)
    if words and words[-1].lower() == "agent":
        words.pop()
    return "".join(word[:1].upper() + word[1:] for word in words)


def _ensure_suffix(text: str, suffix: str) -> str:
    return text if text.endswith(suffix) else text + suffix


def agent_class_name(raw: str) -> str:
    return _pascal(raw) or "Agent"


def _project_name(raw: str) -> str:
    words = [word.lower() for word in _words(raw)]
    if len(words) > 1 and words[-1] == "agent":
        words.pop()
    return "-".join(words) or "agent"


def bat_adk_extras(model_provider: str) -> str:
    """``telemetry`` makes the SDK emit the spans `bat eval` reads; the
    provider's extra brings its LangChain integration."""
    provider = model_provider.lower()
    if provider in {*PROVIDER_API_KEY_VAR, "ollama"}:
        return f"{provider},telemetry"
    return "telemetry"


def api_key_line(model_provider: str) -> str:
    key_var = PROVIDER_API_KEY_VAR.get(model_provider.lower())
    if key_var:
        return f"{key_var}="
    return f"# The '{model_provider}' provider needs no API key."


def resolve_telemetry_privacy(level: str | None) -> str:
    """The ``telemetry_privacy_floor`` a scaffolded agent passes, ``none``
    by default.

    Raises:
        ValueError: On an unknown level, which bat-adk would silently read
            as ``none`` and so export in the clear.
    """
    if level is None:
        return "none"
    normalized = level.strip().lower()
    if normalized not in PRIVACY_LEVELS:
        raise ValueError(
            f"Unknown telemetry privacy level {level!r}; "
            f"expected one of {', '.join(PRIVACY_LEVELS)}."
        )
    return normalized


def _client_specs(clients: list[str] | None) -> dict[str, str]:
    """File stem -> class name of each LLM client to generate."""
    specs: dict[str, str] = {}
    for raw in clients or []:
        pascal = _pascal(raw)
        if pascal:
            stem = "_".join(_words(raw)).lower()
            specs.setdefault(
                _ensure_suffix(stem, "_client"),
                _ensure_suffix(pascal, "Client"),
            )
    return specs or {"example_client": "ExampleClient"}


def graph_substitutions(clients: list[str] | None) -> dict[str, str]:
    specs = _client_specs(clients).items()
    return {
        "CLIENT_IMPORTS": "\n".join(
            f"from .llm_clients.{stem} import {name}" for stem, name in specs
        ),
        "CLIENT_SETUP": "\n\n".join(
            f"        self.{stem} = {name}(\n            tools=[],\n        )"
            for stem, name in specs
        ),
    }


def write_llm_clients(
    directory: Path, *, clients: list[str] | None, force: bool
) -> list[Path]:
    """Write the client modules, then the package ``__init__`` re-exporting
    every client on disk under the class name its file declares."""
    files = {
        f"{stem}.py": render(_CLIENT_TEMPLATE, {"CLASS_NAME": name})
        for stem, name in _client_specs(clients).items()
    }
    written = write_files(directory, files, force=force)

    exports = ""
    for path in sorted(directory.glob("*_client.py")):
        match = _CLASS.search(path.read_text(encoding="utf-8"))
        if match:
            exports += f"from .{path.stem} import {match.group(1)}\n"
    init = directory / "__init__.py"
    content = _CLIENTS_INIT_HEADER + exports
    if not init.is_file() or init.read_text(encoding="utf-8") != content:
        init.write_text(content, encoding="utf-8")
        written.append(init)
    return written


def create_agent_scaffold(
    target_dir: Path,
    *,
    force: bool,
    clients: list[str] | None,
    port: int,
    model: str,
    model_provider: str,
    class_name_source: str,
    telemetry_privacy: str | None,
) -> list[Path]:
    """Write a standalone agent into ``target_dir``. Class names keep the
    casing of ``class_name_source``; everything else follows the folder."""
    floor = resolve_telemetry_privacy(telemetry_privacy)
    ensure_empty_dir(target_dir, force=force)

    project = _project_name(target_dir.name)
    substitutions = {
        "AGENT_NAME": target_dir.name,
        "AGENT_CLASS_NAME": agent_class_name(class_name_source),
        "PROJECT_NAME": project,
        "PROJECT_DESCRIPTION": f"{project.upper()} Agent",
        "BAT_ADK_EXTRAS": bat_adk_extras(model_provider),
        "BAT_ADK_VERSION": BAT_ADK_VERSION,
        "PORT": str(port),
        "MODEL": model,
        "MODEL_PROVIDER": model_provider,
        "API_KEY_LINE": api_key_line(model_provider),
        "TELEMETRY_PRIVACY_FLOOR": floor,
        **graph_substitutions(clients),
    }
    files = {
        name.removesuffix(".template"): render(
            TEMPLATES_DIR / name, substitutions
        )
        for name in template_files(TEMPLATES_DIR)
        if name != _CLIENT_TEMPLATE.name
    }
    return write_files(target_dir, files, force=True) + write_llm_clients(
        target_dir / "src" / "llm_clients", clients=clients, force=force
    )
