[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bat-cli"
version = "0.1.0"
description = "CLI tool to interact with BAT agents"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typer>=0.12.3",
    "PyYAML>=6.0",
    "pydantic>=2.10.6",
]

[dependency-groups]
dev = [
    "pytest>=8.0",
]
packaging = [
    "pyinstaller>=6.0",
]

[project.scripts]
bat = "cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
create = [
    "templates/agent/*",
    "templates/agent/.*",
    "templates/agent/src/*",
    "templates/agent/src/llm_clients/*",
    "templates/agent/tests/*",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
